### ISSUE TITLE
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of long from String value '2018-06-13': not a valid Long value

### ISSUE THREAD

**Issue by guilhebl** [Chabane/bigdata-spark-kafka-full-example#13]
From following the steps in README.MD instructions I was able to build the network and start the containers successfully but when saving a flight info I got the exception above (showing up in the logs of 
streaming_flink_dev)

When sending a flight Info to HBase trhough Flink streaming (streaming_flink_dev container) it fails throwing this Exception. When changing the mappings to String I was able to see the record being saved in HBase. Provided a fix as a [PR](https://github.com/Chabane/bigdata-playground/pull/12)

**Comment by Chabane** [comment]
Thanks for your contribution 👍 
You are right
