### ISSUE TITLE
error TS2307: Cannot find module 'rxjs/rx'.

### ISSUE THREAD

**Issue by jear** [Chabane/bigdata-spark-kafka-full-example#17]
Hi,
Tried some fix without success. Can you help?

[root@swarm1 docker]# docker-compose up -d  
WARNING: The Docker Engine you're using is running in swarm mode.
......
> search-flight-webapp-client@0.1.0 build:prod /usr/src/app/client
> ng build --prod

Date: 2019-01-30T22:35:04.797Z
Hash: 1fda7bef43e9c167b28b
Time: 11596ms
chunk {0} styles.01b4fd32fd4135b8fcb3.bundle.css (styles) 44.9 kB [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in src/app/dashboard/search-flight/search-flight.component.ts(3,28): error TS2307: Cannot find module 'rxjs/rx'.

**Comment by Chabane** [comment]
Hello,

Thanks for your contribution,

It's strange, because `rxjs/rx` is not used in [search-flight.component.ts](https://github.com/Chabane/bigdata-playground/blob/master/webapp/client/src/app/dashboard/search-flight/search-flight.component.ts#L4)

I'll run `docker-compose up -d`. Maybe it's due to the caret `^` in [package.json](https://github.com/Chabane/bigdata-playground/blob/master/webapp/client/package.json#L39)

**Comment by jear** [comment]
rxjs/rx or rxjs/Rx  ?

**Comment by Chabane** [comment]
do you have the latest version? please make a `git pull`

**Comment by jear** [comment]
from centos 7.x, I need to know the version of yarn, jre/jdk, sbt, mvn, npm ...
Do you create a twitter app just to get the keys ?

**Comment by Chabane** [comment]
good point

yarn >=1.12.3
java >=1.8.0_171
sbt >=1.0.2
mvn >= 3.5.3
npm >=6.4.1
node >= v10.13.0

you need to run the following commands 

```
git clone https://github.com/Chabane/bigdata-playground && cd bigdata-playground # to make sure you are in the correct project
docker network create vnet
cd webapp && yarn && cd client && yarn && cd ../server && yarn && cd ../ && npm run build:dev && cd ../
cd batch/spark && sbt clean package assembly && cd ../..

cd batch/hadoop && mvn clean package && cd ../..
cd streaming/spark && sbt clean assembly && cd ../..
cd streaming/flink && sbt clean assembly && cd ../..
cd streaming/storm && mvn clean package && cd ../..
cd docker
docker-compose -f mongo.yml -f zookeeper.yml -f kafka.yml -f hadoop-hbase.yml -f flink.yml up -d
docker-compose -f dev/webapp.yml up -d
docker-compose -f dev/batch-spark.yml up -d
docker-compose -f dev/batch-hadoop.yml up -d
docker-compose -f dev/streaming-spark.yml up -d
docker-compose -f dev/streaming-flink.yml up -d
docker-compose -f dev/streaming-storm.yml up -d
```
about the twitter app I haven't finish it yet

**Comment by jear** [comment]
ok, better now, missing :
npm install rimraf -g
npm install copyfiles -g

**Comment by Chabane** [comment]
there is no need to run  `npm install rimraf -g` and `npm install copyfiles -g`, unless you have executed the content of `npm run build:dev` command manually

**Comment by jear** [comment]
manually, you mean like at the end of this cmd:
cd webapp && yarn && cd client && yarn && cd ../server && yarn && cd ../ && npm run build:dev && cd ../

**Comment by Chabane** [comment]
if you run `npm run build:dev` npm will look at your `./node_modules/.bin` directory to find `rimraf` and `copyfiles` commands. But if you run `rimraf` or `copyfiles` directly from a terminal, npm will look at your `~/node` directory

**Comment by jear** [comment]
ok thx.
How do you install yarn? npm install yarn -g ?

**Comment by Chabane** [comment]
yes, I will add it in the readme

**Comment by jear** [comment]
ok, I can close. Now need to put that in a production cluser :-)

My notes for Centos:
https://github.com/jear/bigdata-playground-centos7.x-prep
